// const types =  ({
    
//     GET_ERRORS : "GET_ERRORS",
//     GET_SUCCESS : "GET_SUCCESS",
//     USER_LOADING : "USER_LOADING",
//     SET_CURRENT_USER : "SET_CURRENT_USER",
//     USER_ADD : "USER_ADD",
//     USER_UPDATE : "USER_UPDATE",
// })

// export default types

export const GET_ERRORS = "GET_ERRORS";
export const GET_SUCCESS = "GET_SUCCESS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const FEEDS_GET_SUCCESS = "FEEDS_GET_SUCCESS";
export const FEEDS_GET_ERRORS = "FEEDS_GET_ERRORS";
export const FEEDS_ADD_SUCCESS = "FEEDS_ADD_SUCCESS";
export const FEEDS_ADD_ERROR = "FEEDS_ADD_ERROR"
export const EVENTS_GET_SUCCESS = "EVENTS_GET_SUCCESS";
export const EVENTS_GET_ERRORS = "EVENTS_GET_ERRORS";
export const COMMENT_ADD_SUCCESS = "COMMENT_ADD_SUCCESS";
export const COMMENT_ADD_ERROR = "COMMENT_ADD_ERROR";
export const FRIENDS_GET_SUCCESS = "FRIENDS_GET_SUCCESS";
export const FRIENDS_N_GET_SUCCESS = "FRIENDS_N_GET_SUCCESS";
export const FRIENDS_N_GET_ERRORS = "FRIENDS_N_GET_ERRORS";
export const FRIENDS_GET_ERRORS = "FRIENDS_GET_ERRORS";
export const PROFILE_GET_SUCCESS = "PROFILE_GET_SUCCESS";
export const PROFILE_GET_ERRORS = "PROFILE_GET_ERRORS";

export const USER_ADD = "USER_ADD";
export const USER_UPDATE = "USER_UPDATE";

export const SERVICES_GET_SUCCESS = "SERVICES_GET_SUCCESS";
export const SERVICES_GET_ERRORS = "SERVICES_GET_ERRORS";

export const SERVICEDETAIL_GET_SUCCESS = "SERVICEDETAIL_GET_SUCCESS";
export const SERVICEDETAIL_GET_ERRORS = "SERVICEDETAIL_GET_ERRORS";



